# Project information
site_name: 'Loki Docs'
site_url: 'https://sonofotis.github.io/lokidocs/'

# Repository
repo_name: 'lokidocs'
repo_url: 'https://github.com/Sonofotis/lokidocs'

# Copyright
copyright: 'Add Copyright'


# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
     accent: 'green'

  font:
    title: 'Proxima Nova'
    text: 'Roboto Regular'
    code: 'Roboto'
  favicon: 'Loki_favicon32x32.png'
  logo: 'Loki_favicon32x32.png'

nav:
- 'Home': 'index.md'
- Introduction:
  - 'Overview': 'Introduction/Overview.md'
  - 'Where to begin?': 'Introduction/BeginnersGuide.md'
- Wallets: 
  - 'Overview' : 'Wallets/WalletsOverview.md'
  - 'What wallet to use?' : 'Wallets/WhatWalletToUse.md'
  - Web Wallet (LokiLocker): 
      - 'WW Overview' : 'Wallets/WebWallet/WebWalletOverview.md'
      - 'Guides': 'Wallets/WebWallet/Guides.md'
  - Graphical User interface (GUI) Wallet:
      - 'GUI Overview' : 'Wallets/GuiWallet/GUIOverview.md'
      - 'Guides': 'Wallets/GuiWallet/Guides.md'
  - Mobile Wallet:
      - 'Mobile Wallet Overview' : 'Wallets/MobileWallet/MobileWalletOverview.md'
      - 'Android Wallet Guide' : 'Wallets/MobileWallet/Guides.md'
  - Command Line Integrated (CLI) Wallet:
    - 'CLI Overview' : 'Wallets/CliWallet/CLIOverview.md'
    - 'lokid' : 'Wallets/CliWallet/lokid.md'
    - 'Service Node Full Guide': 'Wallets/CliWallet/SNFullGuide.md'
    - 'Compiling Loki from source': 'Wallets/CliWallet/CompilingGuide.md'
    - 'Using Tor': 'Wallets/CliWallet/UsingTor.md'
    - 'Debugging': 'Wallets/CliWallet/Debugging.md'
    - Multisig:
      - '2/2 Multisig': 'Wallets/CliWallet/2of2Multisig.md'
      - '2/3 Multisig': 'Wallets/CliWallet/2of3Multisig.md'
  - RPC Guides:
      - 'Service Node RPC Guide': 'Wallets/RPCGuides/SNRPCGuide.md'
- Mining:
   - 'Proof Of Work' : 'Mining/ProofOfWork.md'
- Service Nodes:
    - 'Overview': 'ServiceNodes/SNOverview.md'
    - 'Staking Requirement' : 'ServiceNodes/StakingRequirement.md'
    - Guides:
      - 'Service Node Full Guide': 'Wallets/CliWallet/SNFullGuide.md'
      - 'Service Node RPC Guide': 'Wallets/RPCGuides/SNRPCGuide.md'
- LokiNet:
    - 'Overview': 'LokiNet/LokiNetOverview.md'
    - 'LLARP': 'LokiNet/LLARP.md'
    - 'SNapps': 'LokiNet/SNapps.md'
    - 'Messenger' : 'LokiNet/Messenger.md'
- Advanced:
   - 'Technical Specs' : 'Advanced/TechnicalSpecs.md'
   - 'Emission Curve' : 'Advanced/EmissionCurve.md'
   - 'Sybil Resistance' : 'Advanced/SybilResistance.md'
- FAQ:
   - 'Emission Curve' : 'Advanced/EmissionCurve.md'
- Contributing:
   - 'Using Github' : 'Contributing/Github.md'
- About:
   - 'To be added' : 'About/loki.md' 

# Customization
extra_css:
  - CSS/style.css
  - CSS/font.css

extra:
  social:
    - type: 'github'
      link: 'https://github.com/loki-project'
    - type: 'twitter'
      link: 'https://twitter.com/loki_project'
    - type: 'telegram'
      link: 'https://t.me/LokiCommunity'
    - type: 'reddit'
      link: 'https://www.reddit.com/r/LokiProject'
    - type: 'youtube'
      link: 'https://www.youtube.com/lokinetwork'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true